### ISSUE TITLE
Unable to locate file "ccle_tcga_ad_cells.p" in the project or at zonodo?

### ISSUE THREAD

**Issue by jaidevjoshi83** [AdorableYoyo/TransPro_a#1]
I am trying to locate the file "ccle_tcga_ad_cells.p" within the project repository, but I couldn't find it. Its not available at the zonodo data repo as wll.  Any assistance in locating the file would be greatly appreciated. Thank you.

**Comment by AdorableYoyo** [comment]
Hi,

Thanks for your interest. 
Please see the latest version: [(https://doi.org/10.5281/zenodo.11036910)]

Best,
Yoyo

**Comment by jaidevjoshi83** [comment]
Thank you!
